# Generated by Django 5.2.4 on 2025-08-13 11:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='IP')),
                ('user_agent', models.TextField(blank=True, max_length=200, null=True, verbose_name='User_Agent')),
                ('visittime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date_Time')),
            ],
        ),
    ]
