# Generated by Django 5.2.4 on 2025-10-20 13:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UplPict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('UpPict_Img', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Загрузка',
                'verbose_name_plural': 'Загрузки',
            },
        ),
        migrations.CreateModel(
            name='Visitors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=20, null=True, verbose_name='IP')),
                ('user_agent', models.TextField(blank=True, max_length=200, null=True, verbose_name='User_Agent')),
                ('ref', models.TextField(blank=True, max_length=200, null=True, verbose_name='Referer')),
                ('visittime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date_Time')),
            ],
            options={
                'verbose_name': 'Визитер',
                'verbose_name_plural': 'Визитеры',
            },
        ),
    ]
