# Generated by Django 5.2.4 on 2025-08-18 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UplPict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('UpPict_Img', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.AlterModelOptions(
            name='visitors',
            options={'verbose_name': 'Визитер', 'verbose_name_plural': 'Визитеры'},
        ),
    ]
