# Generated by Django 5.2.4 on 2025-10-21 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uplpict',
            name='recent',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
