# Generated by Django 5.2.4 on 2025-08-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_uplpict_alter_visitors_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uplpict',
            options={'verbose_name': 'Загрузка', 'verbose_name_plural': 'Загрузки'},
        ),
        migrations.AlterField(
            model_name='uplpict',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
